.TH "src Directory Reference" 3 "Thu Dec 12 2024" "Gestão de refeições" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBficheiros\&.c\fP"
.br
.RI "Implementação de funções para manipulação de ficheiros de dados\&. "
.ti -1c
.RI "file \fBHeader\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "Programa principal para gestão de funcionários, ementas e escolhas no espaço social\&. "
.ti -1c
.RI "file \fBmostrar_dados\&.c\fP"
.br
.in -1c
