.TH "Ementa" 3 "Thu Dec 12 2024" "Gestão de refeições" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ementa
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBdia\fP [10]"
.br
.ti -1c
.RI "char \fBdata\fP [11]"
.br
.ti -1c
.RI "char \fBpratoPeixe\fP [100]"
.br
.ti -1c
.RI "int \fBcaloriasPeixe\fP"
.br
.ti -1c
.RI "char \fBpratoCarne\fP [100]"
.br
.ti -1c
.RI "int \fBcaloriasCarne\fP"
.br
.ti -1c
.RI "char \fBpratoDieta\fP [100]"
.br
.ti -1c
.RI "int \fBcaloriasDieta\fP"
.br
.ti -1c
.RI "char \fBpratoVegetariano\fP [100]"
.br
.ti -1c
.RI "int \fBcaloriasVegetariano\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file Header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int caloriasCarne"

.PP
Definition at line 18 of file Header\&.h\&.
.SS "int caloriasDieta"

.PP
Definition at line 20 of file Header\&.h\&.
.SS "int caloriasPeixe"

.PP
Definition at line 16 of file Header\&.h\&.
.SS "int caloriasVegetariano"

.PP
Definition at line 22 of file Header\&.h\&.
.SS "char data[11]"

.PP
Definition at line 14 of file Header\&.h\&.
.SS "char dia[10]"

.PP
Definition at line 13 of file Header\&.h\&.
.SS "char pratoCarne[100]"

.PP
Definition at line 17 of file Header\&.h\&.
.SS "char pratoDieta[100]"

.PP
Definition at line 19 of file Header\&.h\&.
.SS "char pratoPeixe[100]"

.PP
Definition at line 15 of file Header\&.h\&.
.SS "char pratoVegetariano[100]"

.PP
Definition at line 21 of file Header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Gestão de refeições from the source code\&.
