.TH "Escolha" 3 "Thu Dec 12 2024" "Gestão de refeições" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Escolha
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBdia\fP [10]"
.br
.ti -1c
.RI "int \fBidFuncionario\fP"
.br
.ti -1c
.RI "char \fBtipoPrato\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file Header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char dia[10]"

.PP
Definition at line 26 of file Header\&.h\&.
.SS "int idFuncionario"

.PP
Definition at line 27 of file Header\&.h\&.
.SS "char tipoPrato"

.PP
Definition at line 28 of file Header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Gestão de refeições from the source code\&.
