.TH "Funcionario" 3 "Thu Dec 12 2024" "Gestão de refeições" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Funcionario
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char \fBnome\fP [100]"
.br
.ti -1c
.RI "char \fBnif\fP [10]"
.br
.ti -1c
.RI "char \fBtelefone\fP [10]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples\fP
.in +1c
\fBExemplo\fP\&.
.PP
Definition at line 5 of file Header\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int id"

.PP
Definition at line 6 of file Header\&.h\&.
.SS "char nif[10]"

.PP
Definition at line 8 of file Header\&.h\&.
.SS "char nome[100]"

.PP
Definition at line 7 of file Header\&.h\&.
.SS "char telefone[10]"

.PP
Definition at line 9 of file Header\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Gestão de refeições from the source code\&.
