.TH "src/main.c" 3 "Thu Dec 12 2024" "Gestão de refeições" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c \- Programa principal para gestão de funcionários, ementas e escolhas no espaço social\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'Header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBFuncionario\fP \fBfuncionarios\fP [100]"
.br
.RI "Array global para armazenar os dados dos funcionários\&. "
.ti -1c
.RI "\fBEmenta\fP \fBementas\fP [50]"
.br
.RI "Array global para armazenar os dados das ementas\&. "
.ti -1c
.RI "\fBEscolha\fP \fBescolhas\fP [200]"
.br
.RI "Array global para armazenar as escolhas realizadas pelos utentes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Programa principal para gestão de funcionários, ementas e escolhas no espaço social\&. 

Este programa realiza a leitura de dados de funcionários, ementas e escolhas de ficheiros específicos e apresenta informações relevantes, como:
.IP "\(bu" 2
Lista de funcionários
.IP "\(bu" 2
Ementas da semana
.IP "\(bu" 2
Escolhas realizadas pelos utentes
.IP "\(bu" 2
Refeições solicitadas para um dia específico
.PP
.PP
\fBAuthor\fP
.RS 4
[Seu Nome] 
.RE
.PP
\fBDate\fP
.RS 4
[Data Atual] 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 48 of file main\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBEmenta\fP ementas[50]"

.PP
Array global para armazenar os dados das ementas\&. 
.PP
Definition at line 23 of file main\&.c\&.
.SS "\fBEscolha\fP escolhas[200]"

.PP
Array global para armazenar as escolhas realizadas pelos utentes\&. 
.PP
Definition at line 26 of file main\&.c\&.
.SS "\fBFuncionario\fP funcionarios[100]"

.PP
Array global para armazenar os dados dos funcionários\&. 
.PP
\fBExamples\fP
.in +1c
\fBExemplo\fP\&.
.PP
Definition at line 20 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Gestão de refeições from the source code\&.
