.TH "src/mostrar_dados.c" 3 "Thu Dec 12 2024" "Gestão de refeições" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mostrar_dados.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'Header\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmostrarFuncionarios\fP (const \fBFuncionario\fP \fBfuncionarios\fP[], int numFuncionarios)"
.br
.ti -1c
.RI "void \fBmostrarEmentas\fP (const \fBEmenta\fP \fBementas\fP[], int numEmentas)"
.br
.ti -1c
.RI "void \fBmostrarEscolhas\fP (const \fBEscolha\fP \fBescolhas\fP[], int numEscolhas)"
.br
.ti -1c
.RI "void \fBRefeicoesPorDia\fP (const \fBFuncionario\fP \fBfuncionarios\fP[], int numFuncionarios, const \fBEmenta\fP \fBementas\fP[], int numEmentas, const \fBEscolha\fP \fBescolhas\fP[], int numEscolhas, const char *diaProcurado)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mostrarEmentas (const \fBEmenta\fP ementas[], int numEmentas)"

.PP
Definition at line 22 of file mostrar_dados\&.c\&.
.SS "void mostrarEscolhas (const \fBEscolha\fP escolhas[], int numEscolhas)"

.PP
Definition at line 39 of file mostrar_dados\&.c\&.
.SS "void mostrarFuncionarios (const \fBFuncionario\fP funcionarios[], int numFuncionarios)"

.PP
Definition at line 8 of file mostrar_dados\&.c\&.
.SS "void RefeicoesPorDia (const \fBFuncionario\fP funcionarios[], int numFuncionarios, const \fBEmenta\fP ementas[], int numEmentas, const \fBEscolha\fP escolhas[], int numEscolhas, const char * diaProcurado)"

.PP
Definition at line 53 of file mostrar_dados\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Gestão de refeições from the source code\&.
