Header.h
int lerFuncionarios(const char *filename, Funcionario funcionarios[], int maxFuncionarios)
References funcionarios.
Referenced by main.
int lerEmenta(const char *filename, Ementa ementas[], int maxEmentas)
Lê os dados das ementas a partir de um ficheiro.
Esta função lê um ficheiro com formato: dia;data;pratoPeixe;caloriasPeixe;pratoCarne;caloriasCarne;pratoDieta;caloriasDieta;pratoVegetariano;caloriasVegetariano e preenche um array de estruturas do tipo Ementa. filename Caminho do ficheiro a ser lido. ementas Array de estruturas para armazenar os dados. maxEmentas Número máximo de ementas que podem ser armazenadas no array. int Número de ementas lidas com sucesso ou -1 em caso de erro.
References ementas.
Referenced by main.
int lerEscolhas(const char *filename, Escolha escolhas[], int maxEscolhas)
Lê as escolhas dos utentes a partir de um ficheiro.
Esta função lê um ficheiro com formato: dia;idFuncionario;tipoPrato e preenche um array de estruturas do tipo Escolha. filename Caminho do ficheiro a ser lido. escolhas Array de estruturas para armazenar os dados. maxEscolhas Número máximo de escolhas que podem ser armazenadas no array. int Número de escolhas lidas com sucesso ou -1 em caso de erro.
References escolhas.
Referenced by main.
int gravarFuncionarios(const char *filename, const Funcionario funcionarios[], int numFuncionarios)
Grava os dados dos funcionários em um ficheiro.
Escreve o conteúdo de um array de estruturas do tipo Funcionario em um ficheiro com formato: id;nome;nif;telefone filename Caminho do ficheiro onde os dados serão gravados. funcionarios Array de estruturas contendo os dados a serem gravados. numFuncionarios Número de funcionários no array. int Retorna 0 em caso de sucesso ou -1 em caso de erro.
References funcionarios.
int gravarEmenta(const char *filename, const Ementa ementas[], int numEmentas)
int gravarEscolhas(const char *filename, const Escolha escolhas[], int numEscolhas)
void mostrarFuncionarios(const Funcionario funcionarios[], int numFuncionarios)
References funcionarios.
Referenced by main.
void mostrarEmentas(const Ementa ementas[], int numEmentas)
References ementas.
Referenced by main.
void mostrarEscolhas(const Escolha escolhas[], int numEscolhas)
References escolhas.
Referenced by main.
void RefeicoesPorDia(const Funcionario funcionarios[], int numFuncionarios, const Ementa ementas[], int numEmentas, const Escolha escolhas[], int numEscolhas, const char *diaProcurado)
References ementas, escolhas, funcionarios, Ementa::pratoCarne, Ementa::pratoDieta, Ementa::pratoPeixe, Ementa::pratoVegetariano.
Referenced by main.