mostrar_dados.c
void mostrarFuncionarios(const Funcionario funcionarios[], int numFuncionarios)
References funcionarios.
Referenced by main.
void mostrarEmentas(const Ementa ementas[], int numEmentas)
References ementas.
Referenced by main.
void mostrarEscolhas(const Escolha escolhas[], int numEscolhas)
References escolhas.
Referenced by main.
void RefeicoesPorDia(const Funcionario funcionarios[], int numFuncionarios, const Ementa ementas[], int numEmentas, const Escolha escolhas[], int numEscolhas, const char *diaProcurado)
References ementas, escolhas, funcionarios, Ementa::pratoCarne, Ementa::pratoDieta, Ementa::pratoPeixe, Ementa::pratoVegetariano.
Referenced by main.